name       : pangox-compat
version    : 0.0.2
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/pangox-compat/0.0/pangox-compat-0.0.2.tar.xz : 552092b3b6c23f47f4beee05495d0f9a153781f62a1c4b7ec53857a37dfce046
license    : LGPL-2.0
summary    : X Window System font support for Pango
description: |
    X Window System font support for Pango
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(pango)
    - pkgconfig(x11)
libsplit : no
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
